#!/usr/bin/env python3
"""Extract matplotlib colormap data into src/primitives/colormap-data.lisp.

Continuous maps are sampled as 256-row LUTs (exact parity with matplotlib
output regardless of its internal segment/list representation); qualitative
maps keep their exact entry lists. Maps already registered by hand in
colormaps.lisp are skipped.

Regenerate with:  .venv/bin/python tools/extract_colormaps.py
"""
import numpy as np
import matplotlib

# Already registered in colormaps.lisp — skip.
EXISTING = {
    'binary', 'gray', 'grey', 'autumn', 'spring', 'summer', 'winter',
    'cool', 'hot', 'jet', 'coolwarm',
    'blues', 'greens', 'greys', 'reds', 'rdbu', 'rdylgn', 'spectral',
    'viridis', 'plasma', 'inferno', 'magma', 'cividis',
}

# Continuous maps to sample as 256-row LUTs.
CONTINUOUS = [
    # perceptually uniform + misc
    'turbo', 'cubehelix', 'terrain', 'ocean', 'rainbow', 'nipy_spectral',
    'gnuplot', 'gnuplot2', 'CMRmap', 'brg', 'gist_earth', 'gist_stern',
    'gist_rainbow', 'gist_heat', 'gist_gray', 'gist_yarg', 'gist_ncar',
    'bone', 'copper', 'pink', 'afmhot', 'Wistia',
    # sequential (ColorBrewer-derived)
    'Oranges', 'Purples', 'YlOrBr', 'YlOrRd', 'OrRd', 'PuRd', 'RdPu',
    'BuPu', 'GnBu', 'PuBu', 'YlGnBu', 'PuBuGn', 'BuGn', 'YlGn',
    # diverging
    'PiYG', 'PRGn', 'BrBG', 'PuOr', 'RdGy', 'RdYlBu', 'seismic', 'bwr',
    # cyclic
    'twilight', 'twilight_shifted', 'hsv',
    # sequential2
    'spring', 'summer',  # skipped by EXISTING; kept for clarity
]

# Qualitative maps: exact entry lists.
QUALITATIVE = [
    'tab10', 'tab20', 'tab20b', 'tab20c',
    'Set1', 'Set2', 'Set3', 'Pastel1', 'Pastel2', 'Dark2', 'Accent',
    'Paired',
]


def hex_string(rows):
    """Pack rows as one RRGGBB hex string per map: compiles instantly
    (SBCL's constant coalescing is quadratic over big quoted lists) and
    8-bit channels match the precision of the rendered output."""
    return "".join(
        f"{round(r*255):02X}{round(g*255):02X}{round(b*255):02X}"
        for r, g, b in rows)


def main():
    lut_entries = []
    for name in CONTINUOUS:
        if name.lower() in EXISTING:
            continue
        cmap = matplotlib.colormaps[name]
        lut = cmap(np.linspace(0.0, 1.0, 256))[:, :3]
        lut_entries.append((name, lut))

    listed_entries = []
    for name in QUALITATIVE:
        if name.lower() in EXISTING:
            continue
        cmap = matplotlib.colormaps[name]
        colors = np.asarray(cmap.colors)[:, :3]
        listed_entries.append((name, colors))

    with open('src/primitives/colormap-data.lisp', 'w') as f:
        f.write(f""";;;; colormap-data.lisp — matplotlib colormap tables (GENERATED)
;;;;
;;;; Generated by tools/extract_colormaps.py from matplotlib
;;;; {matplotlib.__version__}. Continuous maps are 256-row LUT samples of
;;;; the matplotlib colormap (exact output parity); qualitative maps are
;;;; the exact entry lists. Do not edit by hand — rerun the extractor.

(in-package #:cl-matplotlib.primitives)

(defparameter *extended-lut-colormaps*
  '(
""")
        for name, lut in lut_entries:
            f.write(f'    ("{name}" . "{hex_string(lut)}")\n')
        f.write(""")
  "Alist of colormap name -> packed RRGGBB hex LUT string (256 entries),
registered as listed colormaps by initialize-colormaps.")

(defparameter *extended-listed-colormaps*
  '(
""")
        for name, colors in listed_entries:
            f.write(f'    ("{name}" . "{hex_string(colors)}")\n')
        f.write(""")
  "Alist of qualitative colormap name -> packed RRGGBB hex entry string.")
""")
    n = len(lut_entries) + len(listed_entries)
    print(f"Wrote {n} colormaps ({len(lut_entries)} LUT, "
          f"{len(listed_entries)} listed) to src/primitives/colormap-data.lisp")


if __name__ == '__main__':
    main()
